version: '3'

app_network:
   name: fastnetwork
   driver: bridge

services:
  postman_newman:
    build:
      context: . 
      dockerfile: Dockerfile
    image: postman_newman
    command:
      run J_0_collection.json -k
      -e environment.json
      -d data.csv 
      -n 1
      -r htmlextra
      --reporter-htmlextra-Title "Regression Suite Report with 1 Users" 
      --reporter-htmlextra-testPaging
    volumes:
      - .:/etc/newman
    networks:
      - app_network


