version: '3.9'

#networks:
#  app_network: 
#    name: fastnetwork
#    driver: bridge


services:
  core-api-test:
    build:
      context: . 
      dockerfile: Dockerfile
    image: api-test-image
    command:
      run J_0_collection.json -k
      -e environment.json
      -d data.csv 
      -n 1
      -r cli,junit,htmlextra
      --reporter-htmlextra-Title "Regression Suite Report with 1 Users" 
      --reporter-htmlextra-testPaging
      --reporter-htmlextra-browserTitle "API Regression - Core Banking Report" 
      --reporter-htmlextra-export "newman/API_Core_html_report.html"
      --reporter-junit-export "newman/API_Core_junit_report.xml"
    volumes:
      - ./:/etc/newman
 #   networks:
 #     - app_network
 
 eco-api-test:
    build:
      context: . 
      dockerfile: Dockerfile
    image: api-test-image
    command:
      run J_0_collection.json -k
      -e environment.json
      -d data.csv 
      -n 1
      -r cli,junit,htmlextra
      --reporter-htmlextra-Title "Regression Suite Report with 1 Users" 
      --reporter-htmlextra-testPaging
      --reporter-htmlextra-browserTitle "API Regression - Ecosystem Report" 
      --reporter-htmlextra-export "newman/API_ecosystem_html_report.html"
      --reporter-junit-export "newman/API_ecosystem_junit_report.xml"
    volumes:
      - ./:/etc/newman
 #   networks:
 #     - app_network

